CREATE TABLE IF NOT EXISTS users(
    id integer  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    age integer NOT NULL,
    description text
);


 INSERT INTO users (name, age, description)
    VALUES('juancho', 23, 'Using Javascript');